# Generated by Django 2.1.2 on 2019-01-15 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('importance', models.TextField(blank=True)),
                ('facts', models.TextField(blank=True)),
                ('issues', models.TextField(blank=True)),
                ('arguments', models.TextField(blank=True)),
                ('ruling', models.TextField(blank=True)),
                ('discussion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseSubTopic',
            fields=[
                ('sub_topic', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CaseTopic',
            fields=[
                ('topic', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Justice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cj', models.CharField(blank=True, max_length=10, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, default=2019, null=True)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='LawClass',
            fields=[
                ('law_class', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='law_class',
            field=models.ForeignKey(blank=True, db_column='law_class', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='conLaw.LawClass'),
        ),
        migrations.AddField(
            model_name='case',
            name='law_classes',
            field=models.ManyToManyField(related_name='law_classes', to='conLaw.LawClass'),
        ),
        migrations.AddField(
            model_name='case',
            name='maj_opinion',
            field=models.ManyToManyField(blank=True, db_column='maj_opinion', default=None, related_name='maj_opinion', to='conLaw.Justice'),
        ),
        migrations.AddField(
            model_name='case',
            name='related_case',
            field=models.ManyToManyField(blank=True, default=None, related_name='_case_related_case_+', to='conLaw.Case'),
        ),
        migrations.AddField(
            model_name='case',
            name='sub_topic',
            field=models.ManyToManyField(blank=True, to='conLaw.CaseSubTopic'),
        ),
        migrations.AddField(
            model_name='case',
            name='topic',
            field=models.ManyToManyField(to='conLaw.CaseTopic'),
        ),
    ]
