# Generated by Django 2.1.2 on 2019-01-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conLaw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='maj_joined',
            field=models.ManyToManyField(blank=True, db_column='maj_joined', default=None, related_name='maj_joined', to='conLaw.Justice'),
        ),
    ]
