# Generated by Django 2.1.2 on 2019-01-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conLaw', '0002_case_maj_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='concur_joined',
            field=models.ManyToManyField(blank=True, db_column='concur_joined', default=None, related_name='concur_joined', to='conLaw.Justice'),
        ),
        migrations.AddField(
            model_name='case',
            name='concur_opinion',
            field=models.ManyToManyField(blank=True, db_column='concur_opinion', default=None, related_name='concur_opinion', to='conLaw.Justice'),
        ),
    ]
