# Generated by Django 2.1.2 on 2019-01-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conLaw', '0003_auto_20190115_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='concur2_joined',
            field=models.ManyToManyField(blank=True, db_column='concur2_joined', default=None, related_name='concur2_joined', to='conLaw.Justice'),
        ),
        migrations.AddField(
            model_name='case',
            name='concur2_opinion',
            field=models.ManyToManyField(blank=True, db_column='concur2_opinion', default=None, related_name='concur2_opinion', to='conLaw.Justice'),
        ),
        migrations.AddField(
            model_name='case',
            name='concur3_joined',
            field=models.ManyToManyField(blank=True, db_column='concur3_joined', default=None, related_name='concur3_joined', to='conLaw.Justice'),
        ),
        migrations.AddField(
            model_name='case',
            name='concur3_opinion',
            field=models.ManyToManyField(blank=True, db_column='concur3_opinion', default=None, related_name='concur3_opinion', to='conLaw.Justice'),
        ),
        migrations.AddField(
            model_name='case',
            name='dissent2_joined',
            field=models.ManyToManyField(blank=True, db_column='dissent2_joined', default=None, related_name='dissent2_joined', to='conLaw.Justice'),
        ),
        migrations.AddField(
            model_name='case',
            name='dissent2_opinion',
            field=models.ManyToManyField(blank=True, db_column='dissent2_opinion', default=None, related_name='dissent2_opinion', to='conLaw.Justice'),
        ),
        migrations.AddField(
            model_name='case',
            name='dissent3_joined',
            field=models.ManyToManyField(blank=True, db_column='dissent3_joined', default=None, related_name='dissent3_joined', to='conLaw.Justice'),
        ),
        migrations.AddField(
            model_name='case',
            name='dissent3_opinion',
            field=models.ManyToManyField(blank=True, db_column='dissent3_opinion', default=None, related_name='dissent3_opinion', to='conLaw.Justice'),
        ),
        migrations.AddField(
            model_name='case',
            name='dissent_joined',
            field=models.ManyToManyField(blank=True, db_column='dissent_joined', default=None, related_name='dissent_joined', to='conLaw.Justice'),
        ),
        migrations.AddField(
            model_name='case',
            name='dissent_opinion',
            field=models.ManyToManyField(blank=True, db_column='dissent_opinion', default=None, related_name='dissent_opinion', to='conLaw.Justice'),
        ),
        migrations.AddField(
            model_name='case',
            name='justices_np',
            field=models.ManyToManyField(blank=True, db_column='justices_np', default=None, related_name='justices_np', to='conLaw.Justice'),
        ),
    ]
