# Generated by Django 2.1.2 on 2019-01-10 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('set', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag', models.CharField(max_length=35, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='rule',
            name='set',
            field=models.ForeignKey(db_column='set', default=None, on_delete=django.db.models.deletion.CASCADE, to='conduct.RuleSet'),
        ),
        migrations.AddField(
            model_name='rule',
            name='tag',
            field=models.ManyToManyField(to='conduct.Tag'),
        ),
    ]
