# Generated by Django 2.1.2 on 2019-01-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='rule_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
