# Generated by Django 2.1.2 on 2019-01-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduct', '0002_rule_rule_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
